FROM nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04

# install pip and wget
RUN apt-get update && apt-get install -y sudo python-pip wget
RUN pip install --upgrade pip

# install conda
#RUN echo 'export PATH=/opt/conda/bin:$PATH' > /etc/profile.d/conda.sh && \
#    wget --quiet https://repo.continuum.io/miniconda/Miniconda3-4.3.27-Linux-x86_64.sh -O ~/miniconda.sh && \
#    /bin/bash ~/miniconda.sh -b -p /opt/conda && \
#    rm ~/miniconda.sh
#ENV PATH /opt/conda/bin:$PATH

# conda deps (unable to install them with pip)
# RUN conda install -y python=3.5.1 rasterio pyproj

# can install these with some extra work
# https://pypi.python.org/pypi/rasterio
# https://stackoverflow.com/questions/37521682/error-installing-pyproj-in-python-3-5

# pip deps
RUN pip install flake8 awscli lxml shapely boto3==1.5.18 \
    click protobuf==3.5.1 imageio==2.2.0

# apt-get deps
RUN sudo apt-get -y install \
    protobuf-compiler python-pil python-lxml python-tk

# Needed for click to work
ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8

WORKDIR /opt/src/
ENV PYTHONPATH=/opt/src:/opt/src/tf:/opt/src/tf/slim:$PYTHONPATH

COPY run_script.sh /usr/local/bin/
